app:
  env: dev

logging:
  config: classpath:log4j2-dev.xml

http.proxy:
auth:
  dir: auth
  #like 'localhost:19013/api'
  domain: localhost:19013/api
download.dir: download
admob:
  client_id: replace_with_your_client_id
  client_secret: replace_with_your_client_secret

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=true&requireSSL=false&serverTimezone=GMT
    username: root
    password: 12345678
    dbcp2:
      max-total: 320
      min-idle: 5
  jdbc:
    template:
      fetch-size: 1000